### ISSUE TITLE
SQLGetData Variable-Length in parts no change?

### ISSUE THREAD

**Issue by lpillar** [Microsoft/ODBC-Specification#100]
Based on the documentation here https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdata-function#retrieving-variable-length-data-in-parts, it looks like SQLGetData already supports multiple calls to return variable-length data in parts, but the 4.0 spec appears to propose a new way to fetch variable-length data. Is the 4.0 spec proposing a modification to this behavior, or am I missing something?

**Comment by matthew-wozniczka** [comment]
If you're talking about section _3.8 (Variable Length Columns)_, then that's an extension for how to use the existing mechanism to fetch truncated data in parts. Previously there was no way to fetch the data which was truncated while filling a binding.

**Comment by lpillar** [comment]
Ah, that makes sense - thanks!
