### ISSUE TITLE
Behaviour of deferred buffers in interrupted fetches

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#101]
When a [deferred buffer](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/deferred-buffers) is used during a fetch which is interrupted, when is the driver allowed to write into it?

During any call to `SQLFetch`/`SQLFetchScroll`/`SQLNextColumn`?
Only during the 'last' call to those functions (the one that completes the fetch)?
Any time between the call to the initiating `SQLFetch`/`SQLFetchScroll` and the final `SQLNextColumn` which completes the fetch (i.e. from a background thread)? (this would give the most flexibility to the driver)

Can any deferred fields in the ARD be changed (via `SQLSetDescField`/`SQLSetStmtAttr`) during an interrupted fetch? (I would say no)

The spec already has `SQL_ATTR_ROWS_FETCHED_PTR` being populated during `SQLNextColumn`, but I don't think it mentions the others.

**Comment by matthew-wozniczka** [comment]
Does the spec say anything about the analogous situation already existing in ODBC 3.8 when an execution is interrupted with `SQL_NEED_DATA`?

**Comment by mikepizzo** [comment]
The buffers are populated at any time prior to SQLFetch/SQLFetchScroll/SQLNextColumn returning SQL_SUCCESS or SQL_SUCCESS_WITH_INFO.

Currently we allow changing only the descriptor record for the current column during a fetch.

**Comment by mikepizzo** [comment]
The following statement in step 7 of Getting Data During Fetch is meant to clarify that the application can't assume deferred buffers are populated until the fetch concludes:

The application must not assume any bindings have been populated until SQLNextColumn returns `SQL_SUCCESS` or `SQL_SUCCESS_WITH_INFO`.
