### ISSUE TITLE
Does a return escape clause statement qualify as a 'a searched update, insert, or delete statement'?

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#108]
The current spec for [SQLExecute](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlexecute-function) says
>If **SQLExecute** executes a searched update, insert, or delete statement that does not affect any rows at the data source, the call to **SQLExecute** returns SQL_NO_DATA.

So, if a return escape clause query is executed, and the nested DML query does not modify any rows, should we return `SQL_NO_DATA`?

**Comment by mikepizzo** [comment]
I would expect an empty result in this case.

**Comment by mikepizzo** [comment]
Updated spec: 
"If no rows are affected by the statement, an empty result is returned".
