### ISSUE TITLE
Do we need explicit null values for dynamic columns?

### ISSUE THREAD

**Issue by mikepizzo** [Microsoft/ODBC-Specification#11]
Do we need to support explicit null values for dynamic columns (to distinguish null from not present)? If so, how do we delete a dynamic property? use special indicator value SQL_REMOVE_COLUMN, only available if SQL_DYNAMIC_COLUMNS is true? (and maybe not even then?) Make it an ODBC escape? Set a behavior?

**Comment by jduo** [comment]
It would be useful to be able to differentiate between explicit NULL and missing. When a user INSERTs a NULL, writing these as explicit NULLs takes up alot of space on the backend, but with ODBC 3.x there's no way to describe implicit NULL values.

**Comment by mikepizzo** [comment]
Differentiating null from absent would also require we have a way to differentiate in query.  For example, where a column doesn't exist for a particular row.

**Comment by mikepizzo** [comment]
Don't differentiate a null value from a missing dynamic column.  If a dynamic column is set to null it is effectively removed from the row.
