### ISSUE TITLE
How does a client know if a structured column with no backing type is open?

### ISSUE THREAD

**Issue by golamo** [Microsoft/ODBC-Specification#115]
So far I understand

**Structured Column Type**|**DATA_TYPE**|**SQL_DATA_TYPE**
-------------------------------|-----------------|----------------------
Typed | SQL_UDT|?
Unnamed | SQL_ROW | ?
UnTyped | SQL_ROW | SQL_ROW

However it is not clear what will be in SQL_DATA_TYPE for a Unnamed Structured Column?

**Comment by golamo** [comment]
So far I understand

**Structured Column Type**|**DATA_TYPE**|**SQL_DATA_TYPE**
-------------------------------|-----------------|----------------------
Typed | SQL_UDT|?
Unnamed | SQL_ROW | ?
UnTyped | SQL_ROW | SQL_ROW

However it is not clear what will be in SQL_DATA_TYPE for a Unnamed Structured Column?

**Comment by mikepizzo** [comment]
Should clarify in the spec that SQL_DATA_TYPE and DATA_TYPE are both SQL_ROW, SQL_UDT, SQL_MULTISET, and SQL_COLUMNS.

We should remove the concept of "untyped" from section 3.10.1.  Untyped is a special case of an unnamed type that has no defined columns. 

We should replace the last paragraph of 3.10.1 with a statement like "a structured type with no members returns an empty result set. The members of such a type are treated as dynamic columns by the client."

**Comment by mikepizzo** [comment]
Updated spec, but need to determine how the client knows if a structured column with no backing type allows dynamic properties.

**Comment by mikepizzo** [comment]
Perhaps assume any structured column with no backing is open?

**Comment by mikepizzo** [comment]
Added: Clients must assume that instances of structured columns with no backing type may include undeclared (dynamic) columns.
