### ISSUE TITLE
Require SQLGetData to retrieve exception data during a fetch

### ISSUE THREAD

**Issue by mikepizzo** [Microsoft/ODBC-Specification#118]
Currently the spec says that, upon a data exception (length exception, data type exception, or dynamic column) the application can either call SQLGetData to retrieve the value or rebind in which case calling SQLNextColumn will populate that new binding.

It would be much simpler to say that the value for that row can only be fetched via SQLGetData (which may fetch into the bound buffer, but is explicit) rather than requiring the driver to (sometimes) populate this binding.

**Comment by matthew-wozniczka** [comment]
Is this about disallowing the rebinding, or that rebinding is allowed, but won't initially take effect?

If the latter, would the original binding stay in effect until the end of the fetch?

**Comment by mikepizzo** [comment]
We would still allow rebinding *only for rowset size = 1*, which would be applied on the next call to fetch/fetchscroll.
