### ISSUE TITLE
Can multiple nested statements be open on different rows of the same column, concurrently?

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#119]
Consider the following scenario.

1. Application calls `SQLFetch`, which returns with `SQL_DATA_AVAILABLE`
2. Application calls `SQLNextColumn`, then opens a nested statement on column `N`
3. Application calls `SQLNextColumn` again, and opens *another* nested statement on column `N` (but on a separate row)

Can this happen? Section **_6.2.1_** says:
>Multiple calls to SQLGetNestedHandle for the same ParentStatementHandle and Col_or_Param_Num return the same ChildStatementHandle (including any added/modified descriptor fields) unless that handle has been explicitly freed

which seems to forbid this. But it doesn't seem like the handle opened in (2) is implicitly closed by a call to `SQLGetNextColumn` (There is just `Applications SHOULD call SQLCloseCursor on the nested handle when finished reading results.`, which has `SHOULD`), so it's unclear _what_ should happen.

**Comment by matthew-wozniczka** [comment]
From the implementation point of view, it will be much easier to implement if only 1 `version` of a column needed to exist at a time (as is not the case if the example above involves `SQL_METADATA_CHANGED`).

**Comment by mikepizzo** [comment]
Unless GD_CONCURRENT bit has been set in SQL_GETDATA_EXTENSIONS, calling SQLNextColumn should close any nested handles.

GD_CONCURRENT should not be supported for rowset size >1.
