### ISSUE TITLE
Is ODBC 4~ODBC 17?

### ISSUE THREAD

**Issue by ProlificsPanther** [microsoft/ODBC-Specification#142]
This isn't an issue, just a question. Just out of curiosity I am asking.

**Comment by TallTed** [comment]
If you're asking whether v4.0 of the ODBC Specification is the same as (or the basis of) v17 of the ODBC Driver for SQL Server, then "no."

If that's not what you're asking, I think your question needs some more detail... Perhaps with links to the pages or other things you're asking about.

**Comment by ProlificsPanther** [comment]
I am not able to find the driver for this specification, can someone please help me with the download link?
Thanks in advance.

**Comment by TallTed** [comment]
@ProlificsPanther - There is no "driver for this specification" for which to provide a download link. ODBC, Open Database Connectivity, is a data access protocol. The current version of the specification (v`3.80`, though commonly incorrectly labeled as v`3.8`) is found [here](https://docs.microsoft.com/en-us/sql/odbc/microsoft-open-database-connectivity-odbc?view=sqlallproducts-allversions). Possibly, links from that page will help you find the driver download you want.
