### ISSUE TITLE
SAFECONVERT() extensibility

### ISSUE THREAD

**Issue by jduo** [Microsoft/ODBC-Specification#49]
The specification for SAFECONVERT() takes in a finite set of data types for its second parameter, similar to the CONVERT() scalar function. This limits its utility since you can't really specify the shape of structured types or use data-source-specific identifiers.

**Comment by mikepizzo** [comment]
Agreed.  Probably makes sense for the second parameter to be a driver-type, as returned in SQLGetTypeInfo  or SQLStructuredTypes.

**Comment by mikepizzo** [comment]
Proposal: Keep SAFECONVERT for using SQL_TYPES; this is simplest for common built-in types.  Introduce TREAT (or similar) for treating a property as a particular structured type, as well as TYPEOF for getting the type of an (i.e., variant) column (see issue #50).

**Comment by mikepizzo** [comment]
Added a SAFECAST function which takes the type name:

#### 3.3.9 SAFECAST

The SAFECAST function, which can be invoked using the function escape clause, allows an expression to be treated as the specified user-defined or datasource-specific type.

SAFECAST ( *value-exp*, *data-type-name* )

The result of the SAFECAST function is the value of *value-exp* converted to *data-type-name*, where *data-type-name* is datasource-specific type, or the fully qualified name of a user defined or structural type. If the value of *value-exp* cannot be converted to *data-type-name*, the result is null.
