### ISSUE TITLE
Support getting, comparing, grouping by type (i.e., ISTYPE, TYPEOF)

### ISSUE THREAD

**Issue by jduo** [Microsoft/ODBC-Specification#50]
An application user might want to semantically group together variant values for a column that are of the same type.

The SAFECONVERT() function doesn't fully allow for this. For example, you might have a variant V1 for our first parameter, and want SQL_INTEGER values for it.

You can't use WHERE SAFECONVERT(V1, SQL_INTEGER) IS NOT NULL here, since SQL_SMALLINT, SQL_TINYINT, etc values could safely convert to SQL_INTEGERs.

What might make sense would be some dedicated functions for extracting specific types from variant columns.

Also, we should allow for SAFECONVERT() to be used in GROUP BY expressions.

**Comment by mikepizzo** [comment]
so, something like TYPEIS(V1,SQL_SMALLINT) or, more generally, TYPEIS(V1,My.Custom.Type)?

**Comment by mikepizzo** [comment]
Updated title to capture ask.

**Comment by mikepizzo** [comment]
Proposal: Introduce a TYPEOF canonical function that returns the type name of a column. Consider also adding a canonical function to support returning the SQL_TYPE of a column.

**Comment by mikepizzo** [comment]
Added two new canonical functions:

#### 3.3.7 TYPEOF

The TYPEOF function, which can be invoked using the function escape clause, returns the type name of an expression.

TYPEOF ( *value-exp* )

#### 3.3.8 SQLTYPEOF

The SQLTYPEOF function, which can be invoked using the function escape clause, returns the canonical SQLTYPE name of an expression.

SQLTYPEOF ( *value-exp* )
