### ISSUE TITLE
UNNEST operator and variants

### ISSUE THREAD

**Issue by jduo** [Microsoft/ODBC-Specification#51]
What is the behavior when using the UNNEST operator with a variant, where it might be a collection-type on some rows, but not others?

Also, how does UNNEST behave if the collection being unnested does not have a fixed type (perhaps it is an array of variants)?

**Comment by matthew-wozniczka** [comment]
How about if the collection being unnested is NULL? Does it behave the same as if it were an empty collection?

**Comment by mikepizzo** [comment]
Added: 

"If the type of the collection is variant, or the Unnest operator references a dynamic column of an open type, then the Unnest operator returns null for rows in which the column is not defined."
