### ISSUE TITLE
SQLColumns extra columns

### ISSUE THREAD

**Issue by jduo** [Microsoft/ODBC-Specification#52]
Under SQLColumns, there are several new columns added when running an ODBC 4.0 environment. Can these columns also be exposed in other ODBC versions, and just get treated as custom columns in those cases?

**Comment by mikepizzo** [comment]
It's fine for drivers to expose these as custom columns in pre-ODBC 4.0 environments, but clients can't assume the semantics of these columns until 4.0.

**Comment by mikepizzo** [comment]
Added the ability to support new columns without reporting 4.x in catalog functions to section 5.2, ODBC 3.x Drivers.
