### ISSUE TITLE
SQLNextColumn with NULL pointer for Col_or_Param_Num

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#60]
Section _6.1.1_ states:
>Calling SQLNextColumn with a null pointer for Col_or_Param_Num skips the rest of the DATA_AT_FETCH columns for this row.

What about dynamic columns, and bound columns for which length/type exceptions occur?

Also, `for this row` is ambiguous in the context of multi-row fetches.

**Comment by mikepizzo** [comment]
Revised wording:

Calling SQLNextColumn with a null pointer for `Col_or_Param_Num` populates any remaining bound columns, skipping any `DATA_AT_FETCH` or unbound dynamic columns and treating any type or length exceptions according to `SQL_TE_CONTINUE` and `SQL_LE_CONTINUE`, respectively, for the remainder of this row (or row array in the case of array fetch).
