### ISSUE TITLE
Calling SQLFetch/SQLFetchScroll after a previous call returns SQL_DATA_AVAILABLE

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#62]
Section _3.6 (Getting Data during Fetch)_ states:
>Calling SQLFetch/SQLFetchScroll after SQLFetch, SQLFetchScroll, or SQLNextColumn returns SQL_DATA_AVAILABLE skips the remaining columns and begins fetching the next row.

This raises a few questions:

- What exactly does "skips the remaining columns" mean? Does this refer only to `SQL_DATA_AT_FETCH` columns, or to columns which would have triggered `SQL_METADATA_CHANGED`/`SQL_MORE_DATA` returns + dynamic columns as well? If so, what occurs to those bindings?
- Same as in #60, "begins fetching the next row" is ambiguous if the rowset size is greater than 1.

**Comment by matthew-wozniczka** [comment]
Also, what is the difference (if any) in this scenario between calling `SQLNextColumn(NULL)` vs `SQLFetch`/`SQLFetchScroll`?

**Comment by mikepizzo** [comment]
SQLFetch should always advance to the next row(set).

We can require calling SQLNextColumn(Null) prior to calling SQLFetch if it is in a DATA_AVAILABLE state.

**Comment by mikepizzo** [comment]
Updated spec: "Calling SQLFetch or SQLFetchScroll in a data-available state results in a function sequence error."
