### ISSUE TITLE
What defines the 'identity' of a column w.r.t. the IRD?

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#65]
Section _3.9.4.1 (Retrieving Dynamic Columns)_ has the following sentence:
>If the driver encounters a dynamic (unschematized) column that does not match any existing IRD records, ...

What exactly does 'match' mean in this context? Is it driver-defined? Do all descriptor fields have to be equal?

What behaviour is expected/desired in a scenario where a given dynamic column has many different values of the same type (say, SQL_CHAR), but different column sizes? Should the IRD change on every row to show the true size of the column? If so, would these amount to unique IRD entries?

**Comment by matthew-wozniczka** [comment]
This also raises the question of which collation is used to distinguish column names; right now there's only SQL_IDENTIFIER_CASE, which doesn't fully define the collation.

**Comment by mikepizzo** [comment]
"matches"=all descriptor records the same

**Comment by mikepizzo** [comment]
clarified in spec.
