### ISSUE TITLE
SQLGetNestedHandle description wording

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#74]
Section _6.2.1_ states:
>A subsequent call to SQLFreeHandle for a statement handle implicitly closes and frees all child statement handles.

I think this should be changed to something like
>When a statement handle is closed, all of its child statement handles are implicitly closed.

since `SQLFreeHandle` isn't the only way a statement handle can be closed (`SQLDisconnect`).

Also, I assume this works like `SQLDisconnect`, in that it will fail if any of those child nested handles are in the async state, correct?

**Comment by mikepizzo** [comment]
Agreed; good clarification.
