### ISSUE TITLE
SQLGetNestedHandle in prepared state?

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#80]
Section _6.2 (SQLGetNestedHandle)_ says:
>SQLGetNestedHandle can be called for columns containing nested collections or structured columns once the ParentStatementHandle is in a **prepared** or executed state.

I think we need some description of how that works (right now it only describes how it works in the executed state). 

I assume it just means that all child statements are also prepared, and you can describe/bind (non-dynamic) columns in the nested statements before executing the query.

**Comment by mikepizzo** [comment]
Right.

**Comment by mikepizzo** [comment]
Now described in 6.2.1, Usage:

Nested statement handles are in the prepared state and can be used to describe results once the parent statement handle is in the prepared or executed state. Applications can fetch data from the nested statement handle once SQLNextColumn returns the ordinal associated with the nested statement.
