### ISSUE TITLE
SQLGetData returning SQL_DATA_AVAILABLE

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#86]
Section _3.7 (Variable Typed Columns)_ states:
>If set to *True*, SQLFetch, SQLFetchScroll, SQL_NextColumn and **SQLGetData** return `SQL_DATA_AVAILABLE` if new columns are discovered/added to the IRD while retrieving results.

I don't think SQLGetData should do this (same reason as for #67)

**Comment by mikepizzo** [comment]
Agreed. Fixed.

**Comment by lpillar** [comment]
Commit c7035659f0400df623cee6ab182d01a7cc13bea8 closes #86.
