### ISSUE TITLE
Should SQLNextColumn's output-parameter be replaced with a statement attribute?

### ISSUE THREAD

**Issue by matthew-wozniczka** [Microsoft/ODBC-Specification#88]
We could save the application an API call per-interrupted fetch if the application were forced to bind an address for the result of `SQLNextColumn` to be stored in.

The application could then check this memory address to find the column of interest.

The attribute would probably be named 'current column' rather than 'next column'.

**Comment by matthew-wozniczka** [comment]
It could be an error (cursor closed) if the pointer wasn't bound when the fetch was interrupted.

**Comment by mikepizzo** [comment]
Combined with #41 might be interesting, but since we have to have an API call to progress to the next column regardless, I don't think requiring a separate bound buffer for the current column buys us much, and is less consistent with other processing patterns (like SQLParamData)
